/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A requester's own requests, newest first, with their status and need */
        get: operations["my_requests_requests_get"];
        put?: never;
        /**
         * Submit a feature request
         * @description Saves the request as `pending` and returns at once; the intake workflow runs later.
         */
        post: operations["create_request_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/needs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find needs */
        get: operations["list_needs_needs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/needs/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Needs similar to what the requester is typing (embeddings only) */
        get: operations["similar_needs_needs_similar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/needs/{need_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Need */
        get: operations["get_need_needs__need_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/needs/{need_id}/support": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add support (a requester claim)
         * @description 201 the first time, 200 on a repeat by the same requester. Not counted until confirmed. 409 if the need was merged into another one.
         */
        post: operations["add_support_needs__need_id__support_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/needs/{need_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change a need's status (a human product decision) and queue the stakeholder drafts
         * @description Saved at once; the worker then drafts a personal update per supporter and a CS note per account. Nothing is sent until a PM approves each draft. 409 for a merged need or the same status.
         */
        patch: operations["change_status_needs__need_id__status_patch"];
        trace?: never;
    };
    "/needs/{need_id}/updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status changes with their drafted, approved and discarded stakeholder messages (PM view) */
        get: operations["need_updates_needs__need_id__updates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/needs/{need_id}/status-changes/{change_id}/redraft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Draft the stakeholder messages again after drafting failed (spends one model call) */
        post: operations["redraft_needs__need_id__status_changes__change_id__redraft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/triage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The PM inbox: suggestions, claim disputes, the audit sample and failures */
        get: operations["list_triage_triage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/triage/{suggestion_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept a suggestion, confirm a claim, or mark an audit correct */
        post: operations["accept_triage__suggestion_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/triage/{suggestion_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a suggestion or claim, or mark an audit a false merge */
        post: operations["reject_triage__suggestion_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}/unlink": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Undo a link: the request becomes its own need */
        post: operations["unlink_requests__request_id__unlink_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/insights/quadrant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Undecided needs by popularity and strategic fit
         * @description Popular is revenue-weighted demand (D), strategic is the goal-weighted fit (S); cut-offs come from config/priorities.yaml. Needs whose fit isn't rated yet are listed apart.
         */
        get: operations["quadrant_insights_quadrant_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requesters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** People the UI can act as (no auth, spec A3) */
        get: operations["list_requesters_requesters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** AI Ops and the success metrics (spec §10): calls, cost, latency, acceptance, false merges, M1-M3 */
        get: operations["overview_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/updates/{update_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit a draft; the commitment check runs again on the new text */
        patch: operations["edit_updates__update_id__patch"];
        trace?: never;
    };
    "/updates/{update_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve and send to the (simulated) outbox; 409 while commitments are flagged */
        post: operations["approve_updates__update_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/updates/{update_id}/discard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discard a draft */
        post: operations["discard_updates__update_id__discard_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The simulated outbox: approved messages only */
        get: operations["outbox_outbox_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AISource
         * @description Which model (or "offline-baseline") produced an AI value, with which prompt, in which ai_runs row.
         */
        AISource: {
            /** Model */
            model: string | null;
            /** Prompt Version */
            prompt_version: string | null;
            /** Ai Run Id */
            ai_run_id: number | null;
        };
        /** AccountOut */
        AccountOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            segment: components["schemas"]["Segment"];
            /** Arr */
            arr: number;
            /** Is Prospect */
            is_prospect: boolean;
            /** Pipeline Value */
            pipeline_value: number | null;
            /** Renewal Date */
            renewal_date: string | null;
        };
        /** AuditEvent */
        AuditEvent: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "link" | "unlink" | "status" | "decision" | "ai_run";
            /**
             * Actor
             * @description auto, pm (or the PM's name), requester_claim, or the model for ai_run
             */
            actor: string;
            /** Summary */
            summary: string;
            /** Request Id */
            request_id?: number | null;
            /** Model */
            model?: string | null;
        };
        /** CommitmentFlag */
        CommitmentFlag: {
            /** Phrase */
            phrase: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "date" | "timing" | "promise";
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Reason */
            reason: string;
        };
        /**
         * Decision
         * @description Who decided. There is no auth yet (spec A3), so the PM names themselves.
         */
        Decision: {
            /** By */
            by: string;
        };
        /** DecisionResult */
        DecisionResult: {
            /** Id */
            id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "suggestion" | "claim" | "audit";
            /** State */
            state: string;
            /** Audit Verdict */
            audit_verdict: string | null;
            /** Need Id */
            need_id: number | null;
        };
        /** DemandOut */
        DemandOut: {
            /**
             * Value
             * @description D, 0-1: log-scaled weighted revenue over unique accounts
             */
            value: number;
            /**
             * Revenue
             * @description R: ARR x segment weight (customers) + p_win x pipeline x segment weight
             */
            revenue: number;
            /** Customer Revenue */
            customer_revenue: number;
            /** Prospect Revenue */
            prospect_revenue: number;
            /** Accounts */
            accounts: number;
            /** Customers */
            customers: number;
            /** Prospects */
            prospects: number;
            /**
             * Gaps
             * @description Accounts counted with no ARR or pipeline value on record
             */
            gaps: string[];
        };
        /** DraftEdit */
        DraftEdit: {
            /** Body */
            body: string;
            /** By */
            by: string;
        };
        /** DraftOut */
        DraftOut: {
            /** Id */
            id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "requester_update" | "cs_note";
            /** Requester Id */
            requester_id: number | null;
            /** Requester Name */
            requester_name: string | null;
            /** Account Id */
            account_id: number | null;
            /** Account Name */
            account_name: string | null;
            /** Body */
            body: string;
            /**
             * Original Body
             * @description The AI's draft, before any PM edit
             */
            original_body: string;
            /** Edited */
            edited: boolean;
            /**
             * Flags
             * @description The commitment check on the current body (code, not the model)
             */
            flags: components["schemas"]["CommitmentFlag"][];
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "approved" | "discarded" | "superseded";
            /** Approved By */
            approved_by: string | null;
            /** Approved At */
            approved_at: string | null;
            source: components["schemas"]["AISource"] | null;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Field */
            field: string;
            /** Issue */
            issue: string;
        };
        /** ErrorInfo */
        ErrorInfo: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Details
             * @default []
             */
            details: components["schemas"]["ErrorDetail"][];
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorInfo"];
        };
        /** Evidence */
        Evidence: {
            /**
             * Quote
             * @description Verbatim from a request, verified in code
             */
            quote: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "link" | "strategic_fit";
            /** Request Id */
            request_id: number | null;
            /** Goal */
            goal: string | null;
        };
        /** FailedRequest */
        FailedRequest: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Reason */
            reason: string | null;
            /** Attempts */
            attempts: number;
        };
        /** FalseMergeOut */
        FalseMergeOut: {
            /** @description M4: audited auto-links marked false_merge / audited auto-links */
            audited: components["schemas"]["RateOut"];
            /** Target */
            target: number;
            /**
             * Within Target
             * @description Upper bound at or under target; null with no audits
             */
            within_target: boolean | null;
            /** Auto Links */
            auto_links: number;
            /** Undone */
            undone: number;
            /**
             * Undo Rate
             * @description Undone auto-links / auto-links: a lower bound on false merges
             */
            undo_rate: number | null;
        };
        /** GoalRatingOut */
        GoalRatingOut: {
            /** Goal */
            goal: string;
            /** Title */
            title: string;
            /**
             * Weight
             * @description From config/priorities.yaml now, not when the rating was made
             */
            weight: number;
            /**
             * Rating
             * @description 0-3, rated by the model
             */
            rating: number | null;
            /**
             * Contribution
             * @description weight x rating / 3
             */
            contribution: number;
            /** Rationale */
            rationale: string | null;
            /**
             * Quote
             * @description Verified verbatim in the need's requests
             */
            quote: string | null;
            /**
             * Quote Dropped
             * @description The model quoted text that isn't in the requests; it was dropped
             */
            quote_dropped: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LinkInfo
         * @description How the request joined this need: by the intake workflow (auto), a PM, or as the need's first request.
         */
        LinkInfo: {
            /** Actor */
            actor: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Routing Score */
            routing_score: number | null;
            /** Label */
            label: string | null;
            /** Rationale */
            rationale: string | null;
            source: components["schemas"]["AISource"] | null;
        };
        /** M1Out */
        M1Out: {
            /**
             * Processed
             * @description Requests the intake workflow finished: processed or needs review
             */
            processed: number;
            /**
             * Untouched
             * @description No PM link or decision, no open suggestion, not failed
             */
            untouched: number;
            /**
             * Value
             * @description Share of processed requests no PM had to touch
             */
            value: number | null;
            /**
             * Pm Minutes Per 100
             * @description Touched share x 100 requests x 2 minutes (spec A6)
             */
            pm_minutes_per_100: number | null;
        };
        /** M2Out */
        M2Out: {
            /** Claims */
            claims: number;
            /** New Requests */
            new_requests: number;
            /**
             * Deflection
             * @description Claims at the door / (claims + new requests)
             */
            deflection: number | null;
            /** New Need Requests */
            new_need_requests: number;
            /** Relinked By Pm */
            relinked_by_pm: number;
            /**
             * Leakage
             * @description Requests routed to a new need that a PM later linked to an existing one
             */
            leakage: number | null;
            /** Note */
            note: string;
        };
        /** M3Out */
        M3Out: {
            /**
             * Value
             * @description Median seconds from a status change to its last supporter notified
             */
            value: number | null;
            /**
             * Completed
             * @description Status changes whose every personal update is approved
             */
            completed: number;
            /**
             * Pending
             * @description Status changes with personal updates still waiting for approval
             */
            pending: number;
            /**
             * Not Notified
             * @description Supporters whose personal update was discarded or never drafted
             */
            not_notified: number;
            /** Note */
            note: string;
        };
        /** MyRequest */
        MyRequest: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Description */
            description: string;
            status: components["schemas"]["RequestStatus"];
            /** Needs Review Reason */
            needs_review_reason: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Processed At */
            processed_at: string | null;
            need: components["schemas"]["NeedRef"] | null;
        };
        /** NeedDetail */
        NeedDetail: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Problem */
            problem: string;
            /** Persona */
            persona: string | null;
            /** Product Area */
            product_area: string | null;
            status: components["schemas"]["NeedStatus"];
            /**
             * Priority Score
             * @description 0-100, computed when read from current data and config
             */
            priority_score: number;
            breakdown: components["schemas"]["PriorityBreakdown"];
            /**
             * Support Count
             * @description Distinct requesters with a member request or a confirmed support. Staff filing for several customers count once; account_count shows the customers.
             */
            support_count: number;
            /**
             * Claimed Support Count
             * @description Supports still waiting for the intake workflow to confirm them
             */
            claimed_support_count: number;
            /** Request Count */
            request_count: number;
            /** Account Count */
            account_count: number;
            /** Last Request At */
            last_request_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Job To Be Done */
            job_to_be_done: string | null;
            /** Merged Into Id */
            merged_into_id: number | null;
            /** Requests */
            requests: components["schemas"]["NeedRequestOut"][];
            /** Supports */
            supports: components["schemas"]["SupportOut"][];
            /** Accounts */
            accounts: components["schemas"]["AccountOut"][];
            origin: components["schemas"]["NeedOrigin"];
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /**
             * Updates
             * @description Approved updates sent to supporters (drafts are never shown)
             */
            updates: components["schemas"]["UpdateOut"][];
            /**
             * Audit Trail
             * @description Links, unlinks, status changes, decisions and AI runs, newest first
             */
            audit_trail: components["schemas"]["AuditEvent"][];
        };
        /** NeedOrigin */
        NeedOrigin: {
            /**
             * Created By
             * @description ai | pm | seed
             */
            created_by: string;
            source: components["schemas"]["AISource"] | null;
            /** Rationale */
            rationale: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** NeedPage */
        NeedPage: {
            /** Items */
            items: components["schemas"]["NeedSummary"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** NeedRef */
        NeedRef: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Problem */
            problem: string;
            /** Persona */
            persona: string | null;
            /** Product Area */
            product_area: string | null;
        };
        /** NeedRequestOut */
        NeedRequestOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Description */
            description: string;
            source: components["schemas"]["RequestSource"];
            status: components["schemas"]["RequestStatus"];
            /** Requester Name */
            requester_name: string;
            /** Account Name */
            account_name: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            analysis?: components["schemas"]["RequestAnalysis"] | null;
            link?: components["schemas"]["LinkInfo"] | null;
        };
        /**
         * NeedStatus
         * @enum {string}
         */
        NeedStatus: "open" | "planned" | "in_progress" | "shipped" | "declined" | "merged";
        /** NeedSummary */
        NeedSummary: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Problem */
            problem: string;
            /** Persona */
            persona: string | null;
            /** Product Area */
            product_area: string | null;
            status: components["schemas"]["NeedStatus"];
            /**
             * Priority Score
             * @description 0-100, computed when read from current data and config
             */
            priority_score: number;
            breakdown: components["schemas"]["PriorityBreakdown"];
            /**
             * Support Count
             * @description Distinct requesters with a member request or a confirmed support. Staff filing for several customers count once; account_count shows the customers.
             */
            support_count: number;
            /**
             * Claimed Support Count
             * @description Supports still waiting for the intake workflow to confirm them
             */
            claimed_support_count: number;
            /** Request Count */
            request_count: number;
            /** Account Count */
            account_count: number;
            /** Last Request At */
            last_request_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** NeedUpdates */
        NeedUpdates: {
            /**
             * Changes
             * @description Newest first, each with its drafts
             */
            changes: components["schemas"]["StatusChangeOut"][];
        };
        /** OpsMetrics */
        OpsMetrics: {
            /** Runs */
            runs: components["schemas"]["RunStats"][];
            totals: components["schemas"]["OpsTotals"];
            /** @description PM-accepted suggestions / decided suggestions */
            acceptance: components["schemas"]["RateOut"];
            /** @description Guardrail: finished requests that failed to needs_review */
            needs_review: components["schemas"]["RateOut"];
            false_merge: components["schemas"]["FalseMergeOut"];
            m1: components["schemas"]["M1Out"];
            m2: components["schemas"]["M2Out"];
            m3: components["schemas"]["M3Out"];
        };
        /** OpsTotals */
        OpsTotals: {
            /** Calls */
            calls: number;
            /** Cost Usd */
            cost_usd: number;
            /** Processed Requests */
            processed_requests: number;
            /** Cost Per Request */
            cost_per_request: number | null;
        };
        /** OutboxOut */
        OutboxOut: {
            /** Id */
            id: number;
            /** Update Id */
            update_id: number;
            /**
             * Channel
             * @enum {string}
             */
            channel: "requester" | "cs";
            /** Recipient */
            recipient: string;
            /** Subject */
            subject: string;
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PriorityBreakdown */
        PriorityBreakdown: {
            /**
             * Priority
             * @description 0-100, the sum of contributions
             */
            priority: number;
            /**
             * Contributions
             * @description Points per component: 100 x weight x value
             */
            contributions: {
                [key: string]: number;
            };
            /**
             * Weights
             * @description Weights used; renormalised while strategic is unrated
             */
            weights: {
                [key: string]: number;
            };
            demand: components["schemas"]["DemandOut"];
            urgency: components["schemas"]["UrgencyOut"];
            strategic: components["schemas"]["StrategicOut"];
            /**
             * Quadrant
             * @description Popular is demand, strategic is S; null while unrated
             */
            quadrant: ("clear_win" | "strategic_bet" | "popular_off_strategy" | "park") | null;
            /**
             * Owner
             * @description The PM team that owns the product area
             */
            owner: string;
        };
        /** QuadrantNeed */
        QuadrantNeed: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Product Area */
            product_area: string | null;
            /** Owner */
            owner: string;
            /** Priority */
            priority: number;
            /** Demand */
            demand: number;
            /** Strategic */
            strategic: number | null;
            /** Account Count */
            account_count: number;
            /** Quadrant */
            quadrant: ("clear_win" | "strategic_bet" | "popular_off_strategy" | "park") | null;
        };
        /** QuadrantView */
        QuadrantView: {
            /**
             * Cutoffs
             * @description Inclusive cut-offs from config/priorities.yaml
             */
            cutoffs: {
                [key: string]: number;
            };
            /**
             * Quadrants
             * @description clear_win, strategic_bet, popular_off_strategy, park; highest priority first
             */
            quadrants: {
                [key: string]: components["schemas"]["QuadrantNeed"][];
            };
            /**
             * Not Rated
             * @description Strategic fit not rated yet (pending, failed or offline)
             */
            not_rated: components["schemas"]["QuadrantNeed"][];
        };
        /** RateOut */
        RateOut: {
            /** K */
            k: number;
            /** N */
            n: number;
            /** Value */
            value: number | null;
            /**
             * Low
             * @description Wilson 95% lower bound
             */
            low: number;
            /**
             * High
             * @description Wilson 95% upper bound
             */
            high: number;
        };
        /**
         * RequestAnalysis
         * @description The extraction step's reading of one request (AI-generated: show source, confidence, rationale).
         */
        RequestAnalysis: {
            /** Need Statement */
            need_statement: string | null;
            /** Problem */
            problem: string | null;
            /** Persona */
            persona: string | null;
            /** Job To Be Done */
            job_to_be_done: string | null;
            /** Proposed Solution */
            proposed_solution: string | null;
            /** Product Area */
            product_area: string | null;
            /** Severity Signal */
            severity_signal: string | null;
            /** Confidence */
            confidence: number | null;
            /** Rationale */
            rationale: string | null;
            source: components["schemas"]["AISource"] | null;
        };
        /** RequestCreate */
        RequestCreate: {
            /** Requester Id */
            requester_id: number;
            /**
             * Account Id
             * @description The customer this is for. Required when staff submit for support, sales or cs.
             */
            account_id?: number | null;
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            source: components["schemas"]["RequestSource"];
        };
        /** RequestOut */
        RequestOut: {
            /** Id */
            id: number;
            /** Requester Id */
            requester_id: number;
            /** Account Id */
            account_id: number | null;
            source: components["schemas"]["RequestSource"];
            /** Title */
            title: string;
            /** Description */
            description: string;
            status: components["schemas"]["RequestStatus"];
            /** Need Id */
            need_id: number | null;
            /** Problem */
            problem: string | null;
            /** Persona */
            persona: string | null;
            /** Job To Be Done */
            job_to_be_done: string | null;
            /** Proposed Solution */
            proposed_solution: string | null;
            /** Product Area */
            product_area: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * RequestSource
         * @enum {string}
         */
        RequestSource: "portal" | "support" | "sales" | "cs" | "internal";
        /**
         * RequestStatus
         * @enum {string}
         */
        RequestStatus: "pending" | "processing" | "processed" | "needs_review";
        /** RequesterOut */
        RequesterOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Account Id */
            account_id: number | null;
            /**
             * Account Name
             * @description None for Brightboard staff
             */
            account_name: string | null;
            segment: components["schemas"]["Segment"] | null;
        };
        /**
         * RoutingParts
         * @description How a routing score was reached (spec §8, ADR 0003). Points are on the score's own scale (0-1).
         *
         *     llm: label points (same_need or nothing) + similarity points + field-agreement points.
         *     baseline (offline): the score is the embedding similarity itself; there is no label or field part.
         */
        RoutingParts: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "llm" | "baseline";
            /** Score */
            score: number | null;
            /** Label */
            label: string | null;
            /**
             * Similarity
             * @description Best cosine similarity; null if it couldn't be recovered
             */
            similarity: number | null;
            /** Area Match */
            area_match: boolean | null;
            /** Persona Match */
            persona_match: boolean | null;
            /** Label Points */
            label_points: number;
            /** Similarity Points */
            similarity_points: number;
            /** Field Points */
            field_points: number;
            /** Auto Threshold */
            auto_threshold: number | null;
            /** Suggest Threshold */
            suggest_threshold: number | null;
        };
        /** RunStats */
        RunStats: {
            /** Step */
            step: string;
            /** Model */
            model: string;
            /** Prompt Version */
            prompt_version: string;
            /** Calls */
            calls: number;
            /** Ok */
            ok: number;
            /** Failure Rate */
            failure_rate: number;
            /** Cost Usd */
            cost_usd: number;
            /** Cost Per Call */
            cost_per_call: number;
            /** P50 Ms */
            p50_ms: number;
            /** P95 Ms */
            p95_ms: number;
        };
        /**
         * Segment
         * @enum {string}
         */
        Segment: "enterprise" | "mid_market" | "smb";
        /**
         * Severity
         * @enum {string}
         */
        Severity: "nice_to_have" | "important" | "blocker";
        /** SimilarNeed */
        SimilarNeed: {
            /** Need Id */
            need_id: number;
            /** Title */
            title: string;
            /** Problem */
            problem: string;
            /** Persona */
            persona: string | null;
            /** Product Area */
            product_area: string | null;
            status: components["schemas"]["NeedStatus"];
            /** Score */
            score: number;
        };
        /**
         * StatusChangeIn
         * @description A product decision (spec §7): who, what, why, and a date only if the PM commits to one.
         */
        StatusChangeIn: {
            /**
             * Status
             * @description merged is set only by merging
             * @enum {string}
             */
            status: "open" | "planned" | "in_progress" | "shipped" | "declined";
            /** Reason */
            reason: string;
            /**
             * Target Date
             * @description Set only if the PM commits to a date
             */
            target_date?: string | null;
            /** By */
            by: string;
        };
        /** StatusChangeOut */
        StatusChangeOut: {
            /** Id */
            id: number;
            /** Need Id */
            need_id: number;
            from_status: components["schemas"]["NeedStatus"];
            to_status: components["schemas"]["NeedStatus"];
            /** By */
            by: string;
            /** Reason */
            reason: string;
            /** Target Date */
            target_date: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Drafts Status */
            drafts_status: ("pending" | "drafted" | "failed" | "superseded") | null;
            /** Drafts Error */
            drafts_error: string | null;
            /** Updates */
            updates: components["schemas"]["DraftOut"][];
        };
        /** StrategicOut */
        StrategicOut: {
            /**
             * Value
             * @description S, 0-1; null until every configured goal is rated
             */
            value: number | null;
            /**
             * Status
             * @description stale: rated against goals that have changed since; re-rated on the next support change
             * @enum {string}
             */
            status: "rated" | "stale" | "pending" | "failed" | "not_rated";
            /** Model */
            model: string | null;
            /** Prompt Version */
            prompt_version: string | null;
            /** Ai Run Id */
            ai_run_id: number | null;
            /** Rated At Accounts */
            rated_at_accounts: number | null;
            /** Rerating Queued */
            rerating_queued: boolean;
            /** Error */
            error: string | null;
            /** Goals */
            goals: components["schemas"]["GoalRatingOut"][];
        };
        /** SupportCreate */
        SupportCreate: {
            /** Requester Id */
            requester_id: number;
            /**
             * Why It Matters
             * @description Omit on a repeat to keep the stored reason
             */
            why_it_matters?: string | null;
            severity: components["schemas"]["Severity"];
        };
        /**
         * SupportLinkStatus
         * @enum {string}
         */
        SupportLinkStatus: "claimed" | "confirmed" | "disputed" | "rejected";
        /** SupportOut */
        SupportOut: {
            /** Id */
            id: number;
            /** Need Id */
            need_id: number;
            /** Requester Id */
            requester_id: number;
            /** Requester Name */
            requester_name: string;
            /** Account Name */
            account_name: string | null;
            /** Why It Matters */
            why_it_matters: string;
            severity: components["schemas"]["Severity"];
            link_status: components["schemas"]["SupportLinkStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** TriageItem */
        TriageItem: {
            /** Id */
            id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "suggestion" | "claim" | "audit" | "auto_link";
            /** Routing Score */
            routing_score: number | null;
            /** Label */
            label: string | null;
            /** Model Confidence */
            model_confidence: number | null;
            /** Rationale */
            rationale: string | null;
            /** Quotes */
            quotes: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** @description Suggestion and audit: the need of the link. Claim: the claimed need */
            need: components["schemas"]["NeedRef"] | null;
            /** @description Claim only: the need the model would pick instead */
            alternative_need: components["schemas"]["NeedRef"] | null;
            request: components["schemas"]["TriageRequest"] | null;
            support: components["schemas"]["TriageSupport"] | null;
            /** @description The run behind this decision */
            source?: components["schemas"]["AISource"] | null;
            routing?: components["schemas"]["RoutingParts"] | null;
        };
        /** TriageList */
        TriageList: {
            /**
             * Items
             * @description Waiting for a decision: suggestions, claims, audit sample
             */
            items: components["schemas"]["TriageItem"][];
            /**
             * Auto Linked
             * @description Auto-links still in place, newest first (at most 50): each can be undone (CLAUDE.md rule 2)
             */
            auto_linked: components["schemas"]["TriageItem"][];
            /**
             * Auto Linked Total
             * @description All auto-links still in place
             */
            auto_linked_total: number;
            /** Needs Review */
            needs_review: components["schemas"]["FailedRequest"][];
        };
        /** TriageRequest */
        TriageRequest: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Need Statement */
            need_statement: string | null;
            /** Persona */
            persona: string | null;
            /** Problem */
            problem?: string | null;
            /** Product Area */
            product_area?: string | null;
            /** Requester Name */
            requester_name?: string | null;
            /** Account Name */
            account_name?: string | null;
            /** Created At */
            created_at?: string | null;
        };
        /** TriageSupport */
        TriageSupport: {
            /** Id */
            id: number;
            /** Why It Matters */
            why_it_matters: string;
            severity: components["schemas"]["Severity"];
            claimed_need: components["schemas"]["NeedRef"] | null;
            /** Reason */
            reason: string | null;
        };
        /** UnlinkResult */
        UnlinkResult: {
            /** Request Id */
            request_id: number;
            /** Need Id */
            need_id: number;
            /** Title */
            title: string;
        };
        /** UpdateOut */
        UpdateOut: {
            /** Id */
            id: number;
            /**
             * Kind
             * @description requester_update (to requester_id) or cs_note (for an account; PM view only)
             */
            kind: string;
            /** Requester Id */
            requester_id: number | null;
            /** Body */
            body: string;
            /** Requester Name */
            requester_name: string | null;
            /** Approved At */
            approved_at: string | null;
        };
        /** UrgencyOut */
        UrgencyOut: {
            /**
             * Value
             * @description U, 0-1: highest severity, plus a renewal within the window
             */
            value: number;
            /** Max Severity */
            max_severity: string | null;
            /** Severity Score */
            severity_score: number;
            /** Renewal Soon */
            renewal_soon: boolean;
            /** Renewing Accounts */
            renewing_accounts: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    my_requests_requests_get: {
        parameters: {
            query: {
                requester_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyRequest"][];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_request_requests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_needs_needs_get: {
        parameters: {
            query?: {
                /** @description Text in the need or its member requests */
                q?: string | null;
                status?: components["schemas"]["NeedStatus"] | null;
                product_area?: string | null;
                /** @description Needs with a request or confirmed support from it */
                segment?: components["schemas"]["Segment"] | null;
                sort?: "priority" | "support" | "recent";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NeedPage"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    similar_needs_needs_similar_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarNeed"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_need_needs__need_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                need_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NeedDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    add_support_needs__need_id__support_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                need_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupportCreate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportOut"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    change_status_needs__need_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                need_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusChangeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusChangeOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    need_updates_needs__need_id__updates_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                need_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NeedUpdates"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    redraft_needs__need_id__status_changes__change_id__redraft_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                change_id: number;
                need_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusChangeOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_triage_triage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriageList"];
                };
            };
        };
    };
    accept_triage__suggestion_id__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suggestion_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reject_triage__suggestion_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suggestion_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    unlink_requests__request_id__unlink_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnlinkResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    quadrant_insights_quadrant_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuadrantView"];
                };
            };
        };
    };
    list_requesters_requesters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequesterOut"][];
                };
            };
        };
    };
    overview_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsMetrics"];
                };
            };
        };
    };
    edit_updates__update_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                update_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    approve_updates__update_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                update_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    discard_updates__update_id__discard_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                update_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    outbox_outbox_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutboxOut"][];
                };
            };
        };
    };
}
