/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a feature request
         * @description Saves the request as `pending` and returns at once; the intake workflow runs later.
         */
        post: operations["create_request_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/needs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find needs */
        get: operations["list_needs_needs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/needs/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Needs similar to what the requester is typing (embeddings only) */
        get: operations["similar_needs_needs_similar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/needs/{need_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Need */
        get: operations["get_need_needs__need_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/needs/{need_id}/support": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add support (a requester claim)
         * @description 201 the first time, 200 on a repeat by the same requester. Not counted until confirmed. 409 if the need was merged into another one.
         */
        post: operations["add_support_needs__need_id__support_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/triage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The PM inbox: suggestions, claim disputes, the audit sample and failures */
        get: operations["list_triage_triage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/triage/{suggestion_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept a suggestion, confirm a claim, or mark an audit correct */
        post: operations["accept_triage__suggestion_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/triage/{suggestion_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a suggestion or claim, or mark an audit a false merge */
        post: operations["reject_triage__suggestion_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}/unlink": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Undo a link: the request becomes its own need */
        post: operations["unlink_requests__request_id__unlink_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/insights/quadrant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Undecided needs by popularity and strategic fit
         * @description Popular is revenue-weighted demand (D), strategic is the goal-weighted fit (S); cut-offs come from config/priorities.yaml. Needs whose fit isn't rated yet are listed apart.
         */
        get: operations["quadrant_insights_quadrant_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requesters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** People the UI can act as (no auth, spec A3) */
        get: operations["list_requesters_requesters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountOut */
        AccountOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            segment: components["schemas"]["Segment"];
            /** Arr */
            arr: number;
            /** Is Prospect */
            is_prospect: boolean;
            /** Pipeline Value */
            pipeline_value: number | null;
            /** Renewal Date */
            renewal_date: string | null;
        };
        /**
         * Decision
         * @description Who decided. There is no auth yet (spec A3), so the PM names themselves.
         */
        Decision: {
            /** By */
            by: string;
        };
        /** DecisionResult */
        DecisionResult: {
            /** Id */
            id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "suggestion" | "claim" | "audit";
            /** State */
            state: string;
            /** Audit Verdict */
            audit_verdict: string | null;
            /** Need Id */
            need_id: number | null;
        };
        /** DemandOut */
        DemandOut: {
            /**
             * Value
             * @description D, 0-1: log-scaled weighted revenue over unique accounts
             */
            value: number;
            /**
             * Revenue
             * @description R: ARR x segment weight (customers) + p_win x pipeline x segment weight
             */
            revenue: number;
            /** Customer Revenue */
            customer_revenue: number;
            /** Prospect Revenue */
            prospect_revenue: number;
            /** Accounts */
            accounts: number;
            /** Customers */
            customers: number;
            /** Prospects */
            prospects: number;
            /**
             * Gaps
             * @description Accounts counted with no ARR or pipeline value on record
             */
            gaps: string[];
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Field */
            field: string;
            /** Issue */
            issue: string;
        };
        /** ErrorInfo */
        ErrorInfo: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Details
             * @default []
             */
            details: components["schemas"]["ErrorDetail"][];
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorInfo"];
        };
        /** FailedRequest */
        FailedRequest: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Reason */
            reason: string | null;
            /** Attempts */
            attempts: number;
        };
        /** GoalRatingOut */
        GoalRatingOut: {
            /** Goal */
            goal: string;
            /** Title */
            title: string;
            /**
             * Weight
             * @description From config/priorities.yaml now, not when the rating was made
             */
            weight: number;
            /**
             * Rating
             * @description 0-3, rated by the model
             */
            rating: number | null;
            /**
             * Contribution
             * @description weight x rating / 3
             */
            contribution: number;
            /** Rationale */
            rationale: string | null;
            /**
             * Quote
             * @description Verified verbatim in the need's requests
             */
            quote: string | null;
            /**
             * Quote Dropped
             * @description The model quoted text that isn't in the requests; it was dropped
             */
            quote_dropped: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NeedDetail */
        NeedDetail: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Problem */
            problem: string;
            /** Persona */
            persona: string | null;
            /** Product Area */
            product_area: string | null;
            status: components["schemas"]["NeedStatus"];
            /**
             * Priority Score
             * @description 0-100, computed when read from current data and config
             */
            priority_score: number;
            breakdown: components["schemas"]["PriorityBreakdown"];
            /**
             * Support Count
             * @description Distinct requesters with a member request or a confirmed support. Staff filing for several customers count once; account_count shows the customers.
             */
            support_count: number;
            /**
             * Claimed Support Count
             * @description Supports still waiting for the intake workflow to confirm them
             */
            claimed_support_count: number;
            /** Request Count */
            request_count: number;
            /** Account Count */
            account_count: number;
            /** Last Request At */
            last_request_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Job To Be Done */
            job_to_be_done: string | null;
            /** Merged Into Id */
            merged_into_id: number | null;
            /** Requests */
            requests: components["schemas"]["NeedRequestOut"][];
            /** Supports */
            supports: components["schemas"]["SupportOut"][];
            /** Accounts */
            accounts: components["schemas"]["AccountOut"][];
        };
        /** NeedPage */
        NeedPage: {
            /** Items */
            items: components["schemas"]["NeedSummary"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** NeedRef */
        NeedRef: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Problem */
            problem: string;
            /** Persona */
            persona: string | null;
            /** Product Area */
            product_area: string | null;
        };
        /** NeedRequestOut */
        NeedRequestOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Description */
            description: string;
            source: components["schemas"]["RequestSource"];
            status: components["schemas"]["RequestStatus"];
            /** Requester Name */
            requester_name: string;
            /** Account Name */
            account_name: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * NeedStatus
         * @enum {string}
         */
        NeedStatus: "open" | "planned" | "in_progress" | "shipped" | "declined" | "merged";
        /** NeedSummary */
        NeedSummary: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Problem */
            problem: string;
            /** Persona */
            persona: string | null;
            /** Product Area */
            product_area: string | null;
            status: components["schemas"]["NeedStatus"];
            /**
             * Priority Score
             * @description 0-100, computed when read from current data and config
             */
            priority_score: number;
            breakdown: components["schemas"]["PriorityBreakdown"];
            /**
             * Support Count
             * @description Distinct requesters with a member request or a confirmed support. Staff filing for several customers count once; account_count shows the customers.
             */
            support_count: number;
            /**
             * Claimed Support Count
             * @description Supports still waiting for the intake workflow to confirm them
             */
            claimed_support_count: number;
            /** Request Count */
            request_count: number;
            /** Account Count */
            account_count: number;
            /** Last Request At */
            last_request_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PriorityBreakdown */
        PriorityBreakdown: {
            /**
             * Priority
             * @description 0-100, the sum of contributions
             */
            priority: number;
            /**
             * Contributions
             * @description Points per component: 100 x weight x value
             */
            contributions: {
                [key: string]: number;
            };
            /**
             * Weights
             * @description Weights used; renormalised while strategic is unrated
             */
            weights: {
                [key: string]: number;
            };
            demand: components["schemas"]["DemandOut"];
            urgency: components["schemas"]["UrgencyOut"];
            strategic: components["schemas"]["StrategicOut"];
            /**
             * Quadrant
             * @description Popular is demand, strategic is S; null while unrated
             */
            quadrant: ("clear_win" | "strategic_bet" | "popular_off_strategy" | "park") | null;
            /**
             * Owner
             * @description The PM team that owns the product area
             */
            owner: string;
        };
        /** QuadrantNeed */
        QuadrantNeed: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Product Area */
            product_area: string | null;
            /** Owner */
            owner: string;
            /** Priority */
            priority: number;
            /** Demand */
            demand: number;
            /** Strategic */
            strategic: number | null;
            /** Account Count */
            account_count: number;
            /** Quadrant */
            quadrant: ("clear_win" | "strategic_bet" | "popular_off_strategy" | "park") | null;
        };
        /** QuadrantView */
        QuadrantView: {
            /**
             * Cutoffs
             * @description Inclusive cut-offs from config/priorities.yaml
             */
            cutoffs: {
                [key: string]: number;
            };
            /**
             * Quadrants
             * @description clear_win, strategic_bet, popular_off_strategy, park; highest priority first
             */
            quadrants: {
                [key: string]: components["schemas"]["QuadrantNeed"][];
            };
            /**
             * Not Rated
             * @description Strategic fit not rated yet (pending, failed or offline)
             */
            not_rated: components["schemas"]["QuadrantNeed"][];
        };
        /** RequestCreate */
        RequestCreate: {
            /** Requester Id */
            requester_id: number;
            /**
             * Account Id
             * @description The customer this is for. Required when staff submit for support, sales or cs.
             */
            account_id?: number | null;
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            source: components["schemas"]["RequestSource"];
        };
        /** RequestOut */
        RequestOut: {
            /** Id */
            id: number;
            /** Requester Id */
            requester_id: number;
            /** Account Id */
            account_id: number | null;
            source: components["schemas"]["RequestSource"];
            /** Title */
            title: string;
            /** Description */
            description: string;
            status: components["schemas"]["RequestStatus"];
            /** Need Id */
            need_id: number | null;
            /** Problem */
            problem: string | null;
            /** Persona */
            persona: string | null;
            /** Job To Be Done */
            job_to_be_done: string | null;
            /** Proposed Solution */
            proposed_solution: string | null;
            /** Product Area */
            product_area: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * RequestSource
         * @enum {string}
         */
        RequestSource: "portal" | "support" | "sales" | "cs" | "internal";
        /**
         * RequestStatus
         * @enum {string}
         */
        RequestStatus: "pending" | "processing" | "processed" | "needs_review";
        /** RequesterOut */
        RequesterOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Account Id */
            account_id: number | null;
            /**
             * Account Name
             * @description None for Brightboard staff
             */
            account_name: string | null;
            segment: components["schemas"]["Segment"] | null;
        };
        /**
         * Segment
         * @enum {string}
         */
        Segment: "enterprise" | "mid_market" | "smb";
        /**
         * Severity
         * @enum {string}
         */
        Severity: "nice_to_have" | "important" | "blocker";
        /** SimilarNeed */
        SimilarNeed: {
            /** Need Id */
            need_id: number;
            /** Title */
            title: string;
            /** Problem */
            problem: string;
            /** Persona */
            persona: string | null;
            /** Product Area */
            product_area: string | null;
            status: components["schemas"]["NeedStatus"];
            /** Score */
            score: number;
        };
        /** StrategicOut */
        StrategicOut: {
            /**
             * Value
             * @description S, 0-1; null until every configured goal is rated
             */
            value: number | null;
            /**
             * Status
             * @description stale: rated against goals that have changed since; re-rated on the next support change
             * @enum {string}
             */
            status: "rated" | "stale" | "pending" | "failed" | "not_rated";
            /** Model */
            model: string | null;
            /** Prompt Version */
            prompt_version: string | null;
            /** Ai Run Id */
            ai_run_id: number | null;
            /** Rated At Accounts */
            rated_at_accounts: number | null;
            /** Rerating Queued */
            rerating_queued: boolean;
            /** Error */
            error: string | null;
            /** Goals */
            goals: components["schemas"]["GoalRatingOut"][];
        };
        /** SupportCreate */
        SupportCreate: {
            /** Requester Id */
            requester_id: number;
            /**
             * Why It Matters
             * @description Omit on a repeat to keep the stored reason
             */
            why_it_matters?: string | null;
            severity: components["schemas"]["Severity"];
        };
        /**
         * SupportLinkStatus
         * @enum {string}
         */
        SupportLinkStatus: "claimed" | "confirmed" | "disputed" | "rejected";
        /** SupportOut */
        SupportOut: {
            /** Id */
            id: number;
            /** Need Id */
            need_id: number;
            /** Requester Id */
            requester_id: number;
            /** Requester Name */
            requester_name: string;
            /** Account Name */
            account_name: string | null;
            /** Why It Matters */
            why_it_matters: string;
            severity: components["schemas"]["Severity"];
            link_status: components["schemas"]["SupportLinkStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** TriageItem */
        TriageItem: {
            /** Id */
            id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "suggestion" | "claim" | "audit";
            /** Routing Score */
            routing_score: number | null;
            /** Label */
            label: string | null;
            /** Model Confidence */
            model_confidence: number | null;
            /** Rationale */
            rationale: string | null;
            /** Quotes */
            quotes: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** @description Suggestion and audit: the need of the link. Claim: the claimed need */
            need: components["schemas"]["NeedRef"] | null;
            /** @description Claim only: the need the model would pick instead */
            alternative_need: components["schemas"]["NeedRef"] | null;
            request: components["schemas"]["TriageRequest"] | null;
            support: components["schemas"]["TriageSupport"] | null;
        };
        /** TriageList */
        TriageList: {
            /** Items */
            items: components["schemas"]["TriageItem"][];
            /** Needs Review */
            needs_review: components["schemas"]["FailedRequest"][];
        };
        /** TriageRequest */
        TriageRequest: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Need Statement */
            need_statement: string | null;
            /** Persona */
            persona: string | null;
        };
        /** TriageSupport */
        TriageSupport: {
            /** Id */
            id: number;
            /** Why It Matters */
            why_it_matters: string;
            severity: components["schemas"]["Severity"];
            claimed_need: components["schemas"]["NeedRef"] | null;
            /** Reason */
            reason: string | null;
        };
        /** UnlinkResult */
        UnlinkResult: {
            /** Request Id */
            request_id: number;
            /** Need Id */
            need_id: number;
            /** Title */
            title: string;
        };
        /** UrgencyOut */
        UrgencyOut: {
            /**
             * Value
             * @description U, 0-1: highest severity, plus a renewal within the window
             */
            value: number;
            /** Max Severity */
            max_severity: string | null;
            /** Severity Score */
            severity_score: number;
            /** Renewal Soon */
            renewal_soon: boolean;
            /** Renewing Accounts */
            renewing_accounts: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_request_requests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_needs_needs_get: {
        parameters: {
            query?: {
                /** @description Text in the need or its member requests */
                q?: string | null;
                status?: components["schemas"]["NeedStatus"] | null;
                product_area?: string | null;
                /** @description Needs with a request or confirmed support from it */
                segment?: components["schemas"]["Segment"] | null;
                sort?: "priority" | "support" | "recent";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NeedPage"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    similar_needs_needs_similar_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarNeed"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_need_needs__need_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                need_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NeedDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    add_support_needs__need_id__support_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                need_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupportCreate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportOut"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_triage_triage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriageList"];
                };
            };
        };
    };
    accept_triage__suggestion_id__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suggestion_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reject_triage__suggestion_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suggestion_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    unlink_requests__request_id__unlink_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnlinkResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    quadrant_insights_quadrant_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuadrantView"];
                };
            };
        };
    };
    list_requesters_requesters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequesterOut"][];
                };
            };
        };
    };
}
